

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Header } from "@/components/Header";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    // <html lang="en" suppressHydrationWarning>
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
        // <div className="mx-auto w-full max-w-7xl">
        //   <Header />
        //   <div className='px-4 py-2'>
        //     {children}
        //   </div>
        // </div>

    //     <ThemeProvider
    //         attribute="class"
    //         defaultTheme="system"
    //         enableSystem
    //         disableTransitionOnChange
    //       >
    //         {children}
    //       </ThemeProvider>
    //   </body>
    // </html>
  return (
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
           
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
             enableSystem
             disableTransitionOnChange
       >
        <Header />
          <main className="contaner">
          
            {children}
            </main>
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    )
}
